POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "77bd16f6-6c63-4ba8-9969-49c83be72133"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a6648b6e-dd8f-4e0a-a0e9-9106baaae0f2",
    "account_id_to": "0a2016a2-c165-4c43-a918-e8e8c0f30b8f",
    "amount": 50
}